[project]
name = "gic-interview"
version = "0.1.0"
description = "Movie seat booking application for GIC interview"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "ruff>=0.11.7",
]
